disabled_rules:
    - trailing_whitespace
    
excluded:
    - Pods
    - Secrets.swift
    
line_length: 200

identifier_name:
    allowed_symbols: ["_"]
    min_length:
        warning: 1

type_name:
    allowed_symbols: ["_"]
